# Docker compose file format 3.9 Required Docker Engine 19.03.0+
# For more information see: https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3.9'

services:
  person-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: person-api
    image: person-api:latest
    ports:
      - "8080:8080"